import { Lesson } from "../../types/dtma-lms";

export const lessons: Lesson[] = [
  // Digital Strategy Playbook
  {
    id: "lesson-ds-1",
    courseId: "course-digital-strategy",
    title: "Set the Digital Ambition",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 20,
    content: "Align on the business ambition, value pools, and success KPIs.",
  },
  {
    id: "lesson-ds-2",
    courseId: "course-digital-strategy",
    title: "Value Case Prioritization",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 30,
    content: "Prioritize value cases with impact, feasibility, and risk lenses.",
  },
  {
    id: "lesson-ds-3",
    courseId: "course-digital-strategy",
    title: "Operating Model & Governance",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 35,
    content: "Define governance cadence, roles, and decision forums.",
  },
  {
    id: "lesson-ds-4",
    courseId: "course-digital-strategy",
    title: "Funding & Metrics",
    type: "standard",
    orderIndex: 4,
    estimatedDurationMinutes: 30,
    content: "Link funding to outcomes and set north-star metrics.",
  },
  {
    id: "lesson-ds-5",
    courseId: "course-digital-strategy",
    title: "Roadmap & Dependencies",
    type: "standard",
    orderIndex: 5,
    estimatedDurationMinutes: 35,
    content: "Sequence delivery with dependencies and risk mitigations.",
  },
  {
    id: "lesson-ds-6",
    courseId: "course-digital-strategy",
    title: "Executive Storytelling",
    type: "standard",
    orderIndex: 6,
    estimatedDurationMinutes: 30,
    content: "Craft the executive narrative to align stakeholders.",
  },
  {
    id: "lesson-ds-7",
    courseId: "course-digital-strategy",
    title: "90-Day Launch Plan",
    type: "outro",
    orderIndex: 7,
    estimatedDurationMinutes: 30,
    content: "Finalize the first 90 days of delivery with owners.",
  },

  // Customer Journey Design Sprint
  {
    id: "lesson-cx-1",
    courseId: "course-cx-sprint",
    title: "Select the Journey",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 20,
    content: "Pick a journey and set problem statements with data.",
  },
  {
    id: "lesson-cx-2",
    courseId: "course-cx-sprint",
    title: "Current State & Pain Points",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 30,
    content: "Map the as-is journey and quantify friction.",
  },
  {
    id: "lesson-cx-3",
    courseId: "course-cx-sprint",
    title: "Ideation & Co-creation",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 35,
    content: "Facilitate ideation with squads and SMEs.",
  },
  {
    id: "lesson-cx-4",
    courseId: "course-cx-sprint",
    title: "Prototype & Test",
    type: "standard",
    orderIndex: 4,
    estimatedDurationMinutes: 40,
    content: "Prototype the target journey and run usability tests.",
  },
  {
    id: "lesson-cx-5",
    courseId: "course-cx-sprint",
    title: "Prioritize & Roadmap",
    type: "standard",
    orderIndex: 5,
    estimatedDurationMinutes: 30,
    content: "Prioritize fixes and define impact metrics.",
  },
  {
    id: "lesson-cx-6",
    courseId: "course-cx-sprint",
    title: "Playback & Commitments",
    type: "outro",
    orderIndex: 6,
    estimatedDurationMinutes: 25,
    content: "Playback to stakeholders and assign owners.",
  },

  // Data Storytelling with Impact
  {
    id: "lesson-dswi-1",
    courseId: "course-data-storytelling",
    title: "Finding the Story",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 20,
    content: "Translate analysis into a single, clear narrative.",
  },
  {
    id: "lesson-dswi-2",
    courseId: "course-data-storytelling",
    title: "Choosing the Right Visual",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 35,
    content: "Pick visuals that clarify signal and reduce clutter.",
  },
  {
    id: "lesson-dswi-3",
    courseId: "course-data-storytelling",
    title: "Structuring the Deck",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 35,
    content: "Build executive-friendly slides and headlines.",
  },
  {
    id: "lesson-dswi-4",
    courseId: "course-data-storytelling",
    title: "Delivery & Presence",
    type: "standard",
    orderIndex: 4,
    estimatedDurationMinutes: 30,
    content: "Rehearse delivery, objections, and follow-ups.",
  },
  {
    id: "lesson-dswi-5",
    courseId: "course-data-storytelling",
    title: "Publish the Insight Brief",
    type: "outro",
    orderIndex: 5,
    estimatedDurationMinutes: 40,
    content: "Pull everything into a concise, shareable brief.",
  },

  // Modern Web Architecture Essentials
  {
    id: "lesson-mwa-1",
    courseId: "course-modern-web-architecture",
    title: "Architecture Trade-offs",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 25,
    content: "Choose patterns that balance speed, cost, and resilience.",
  },
  {
    id: "lesson-mwa-2",
    courseId: "course-modern-web-architecture",
    title: "Environments & CI/CD",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 40,
    content: "Set up environments, pipelines, and release strategies.",
  },
  {
    id: "lesson-mwa-3",
    courseId: "course-modern-web-architecture",
    title: "APIs & Integration",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 35,
    content: "Design APIs and integration points that scale.",
  },
  {
    id: "lesson-mwa-4",
    courseId: "course-modern-web-architecture",
    title: "Frontend & Edge",
    type: "standard",
    orderIndex: 4,
    estimatedDurationMinutes: 35,
    content: "Modern frontend patterns, edge, and caching strategies.",
  },
  {
    id: "lesson-mwa-5",
    courseId: "course-modern-web-architecture",
    title: "Observability & Reliability",
    type: "standard",
    orderIndex: 5,
    estimatedDurationMinutes: 35,
    content: "Logging, metrics, tracing, and incident handling.",
  },
  {
    id: "lesson-mwa-6",
    courseId: "course-modern-web-architecture",
    title: "Security & Compliance",
    type: "standard",
    orderIndex: 6,
    estimatedDurationMinutes: 30,
    content: "Security considerations for regulated environments.",
  },
  {
    id: "lesson-mwa-7",
    courseId: "course-modern-web-architecture",
    title: "Reference Architecture",
    type: "outro",
    orderIndex: 7,
    estimatedDurationMinutes: 40,
    content: "Assemble and review the reference architecture pack.",
  },

  // Lean Service Operations
  {
    id: "lesson-lo-1",
    courseId: "course-lean-ops",
    title: "Map the Current State",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 20,
    content: "Identify bottlenecks, queues, and rework in the process.",
  },
  {
    id: "lesson-lo-2",
    courseId: "course-lean-ops",
    title: "SLA & KPI Design",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 35,
    content: "Define SLAs and metrics with clear ownership.",
  },
  {
    id: "lesson-lo-3",
    courseId: "course-lean-ops",
    title: "Automation Opportunities",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 35,
    content: "Spot automation candidates and design guardrails.",
  },
  {
    id: "lesson-lo-4",
    courseId: "course-lean-ops",
    title: "Change & Adoption",
    type: "standard",
    orderIndex: 4,
    estimatedDurationMinutes: 30,
    content: "Plan change management and frontline enablement.",
  },
  {
    id: "lesson-lo-5",
    courseId: "course-lean-ops",
    title: "Control Plan",
    type: "standard",
    orderIndex: 5,
    estimatedDurationMinutes: 30,
    content: "Build a control plan and dashboards to keep gains.",
  },
  {
    id: "lesson-lo-6",
    courseId: "course-lean-ops",
    title: "30-Day Backlog",
    type: "outro",
    orderIndex: 6,
    estimatedDurationMinutes: 20,
    content: "Create a 30-day backlog with owners and checkpoints.",
  },

  // Leading Change in Digital Teams
  {
    id: "lesson-lc-1",
    courseId: "course-leading-change",
    title: "Assess Readiness",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 20,
    content: "Identify sponsors, influencers, and friction points.",
  },
  {
    id: "lesson-lc-2",
    courseId: "course-leading-change",
    title: "Narrative & Messaging",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 35,
    content: "Craft a change story and comms plan for teams.",
  },
  {
    id: "lesson-lc-3",
    courseId: "course-leading-change",
    title: "Rituals & Behaviors",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 30,
    content: "Set rituals that reinforce the new ways of working.",
  },
  {
    id: "lesson-lc-4",
    courseId: "course-leading-change",
    title: "Measure Adoption",
    type: "standard",
    orderIndex: 4,
    estimatedDurationMinutes: 30,
    content: "Track adoption signals and intervene early.",
  },
  {
    id: "lesson-lc-5",
    courseId: "course-leading-change",
    title: "Action Plan",
    type: "outro",
    orderIndex: 5,
    estimatedDurationMinutes: 35,
    content: "Publish a four-week adoption plan with owners.",
  },
];
