apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dtma-ingress
  namespace: dtma
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod   # 🔹 Reference staging ClusterIssuer
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - apps.digitalqatalyst.com   # 🔹 Replace with your domain
    secretName: dtma-tls # 🔹 Secret will be created automatically
  rules:
  - host: apps.digitalqatalyst.com   # 🔹 Replace with your domain
    http:
      paths:
      - path: /dtma
        pathType: Prefix
        backend:
          service:
            name: dtma-service
            port:
              number: 80
      