apiVersion: v1
kind: Secret
metadata:
  name: dtma-secret
type: Opaque
stringData:
  VITE_AZURE_CLIENT_ID: "66ab04e3-a85d-48f1-b7a9-db7fdedd5e9d"
  VITE_AZURE_TENANT_ID: "2d664c1c-c510-4764-af80-fe7c49c1e192"
  # VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnbXlic2thY29tY2RnZG5nb2x6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2NTM0MDEsImV4cCI6MjA4MDIyOTQwMX0.iwNLBgOsE1k8Eb3noMhJ4kCZX6b5oLdq-0B5S7CcPpo"
  VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzczMTU1MTU0LCJleHAiOjIwODg1MTUxNTR9.IE1G_CoLW5BYePvu975_w2cfuT7Z2ddWFfPLjw5-RdE"
