import { Lesson } from "../../types/dtma-lms";

export const lessons: Lesson[] = [
  {
    id: "lesson-course-accelerating-dt-e4-1",
    courseId: "course-accelerating-dt-e4",
    title: "Why Digital Transformations Stall",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 12,
    content: "Looks at common reasons digital transformation efforts slow down or fail.",
  },
  {
    id: "lesson-course-accelerating-dt-e4-2",
    courseId: "course-accelerating-dt-e4",
    title: "Levers That Accelerate Transformation",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 18,
    content: "Introduces practical levers—like sequencing, governance, and focus—that speed up transformation.",
  },
  {
    id: "lesson-course-accelerating-dt-e4-3",
    courseId: "course-accelerating-dt-e4",
    title: "Prioritizing and Sequencing Initiatives",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 18,
    content: "Walks through how to prioritize initiatives and create a realistic transformation sequence.",
  },
  {
    id: "lesson-course-accelerating-dt-e4-4",
    courseId: "course-accelerating-dt-e4",
    title: "Designing an Acceleration Roadmap",
    type: "outro",
    orderIndex: 4,
    estimatedDurationMinutes: 10,
    content: "Helps you sketch a simple acceleration roadmap tailored to your organization.",
  },
  {
    id: "lesson-course-building-ai-driven-orgs-1",
    courseId: "course-building-ai-driven-orgs",
    title: "What Does “AI-Driven” Really Mean?",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 15,
    content: "Clarifies what it means to be AI-driven beyond using a few AI tools.",
  },
  {
    id: "lesson-course-building-ai-driven-orgs-2",
    courseId: "course-building-ai-driven-orgs",
    title: "AI-Enabled Processes and Decisions",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 20,
    content: "Explores patterns for embedding AI into processes and decisions across the organization.",
  },
  {
    id: "lesson-course-building-ai-driven-orgs-3",
    courseId: "course-building-ai-driven-orgs",
    title: "Operating Model and Change Implications",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 20,
    content: "Discusses how AI changes roles, structures, and operating models and what this means for change management.",
  },
  {
    id: "lesson-course-building-ai-driven-orgs-4",
    courseId: "course-building-ai-driven-orgs",
    title: "Sketching an AI-Driven Roadmap",
    type: "outro",
    orderIndex: 4,
    estimatedDurationMinutes: 10,
    content: "Helps you outline a first-cut roadmap to move your organization toward being more AI-driven.",
  },
  {
    id: "lesson-course-building-dbp-e4-1",
    courseId: "course-building-dbp-e4",
    title: "What Is a Digital Business Platform?",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 12,
    content: "Introduces Digital Business Platforms and how they differ from traditional IT stacks.",
  },
  {
    id: "lesson-course-building-dbp-e4-2",
    courseId: "course-building-dbp-e4",
    title: "Core Towers and Components of a DBP",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 18,
    content: "Breaks down the main towers and components of a DBP and what each is responsible for.",
  },
  {
    id: "lesson-course-building-dbp-e4-3",
    courseId: "course-building-dbp-e4",
    title: "Connecting DBPs to Economy 4.0 Value",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 18,
    content: "Shows how DBPs enable new products, services, and ecosystems within Economy 4.0.",
  },
  {
    id: "lesson-course-building-dbp-e4-4",
    courseId: "course-building-dbp-e4",
    title: "Identifying DBP Opportunities in Your Organization",
    type: "outro",
    orderIndex: 4,
    estimatedDurationMinutes: 10,
    content: "Guides you through spotting first DBP opportunities and framing them for leadership and teams.",
  },
  {
    id: "lesson-course-building-dco-1",
    courseId: "course-building-dco",
    title: "What Makes an Organization “Digital Cognitive”?",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 10,
    content: "Introduces the Digital Cognitive Organization and what sets it apart from traditional organizations.",
  },
  {
    id: "lesson-course-building-dco-2",
    courseId: "course-building-dco",
    title: "The Building Blocks of a DCO",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 15,
    content: "Walks through the main building blocks of a DCO, from strategy to platforms and culture.",
  },
  {
    id: "lesson-course-building-dco-3",
    courseId: "course-building-dco",
    title: "Seeing Your Organization Through a DCO Lens",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 15,
    content: "Helps you look at your own organization and identify where DCO traits are strong or weak.",
  },
  {
    id: "lesson-course-building-dco-4",
    courseId: "course-building-dco",
    title: "DCO Readiness Snapshot",
    type: "quiz",
    orderIndex: 4,
    estimatedDurationMinutes: 10,
    content: "A quick self-assessment to summarize your organization’s current DCO readiness.",
  },
  {
    id: "lesson-course-connecting-e4-dco-1",
    courseId: "course-connecting-e4-dco",
    title: "Economy 4.0 and DCO in One Picture",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 12,
    content: "Recaps Economy 4.0 and introduces Digital Cognitive Organizations as its native operating model.",
  },
  {
    id: "lesson-course-connecting-e4-dco-2",
    courseId: "course-connecting-e4-dco",
    title: "The Anatomy of a Digital Cognitive Organization",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 18,
    content: "Breaks down the main components of a DCO, including strategy, platforms, data, AI, and culture.",
  },
  {
    id: "lesson-course-connecting-e4-dco-3",
    courseId: "course-connecting-e4-dco",
    title: "Mapping Economy 4.0 Trends to DCO Design",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 18,
    content: "Shows how macro trends in Economy 4.0 translate into concrete DCO design and operating model choices.",
  },
  {
    id: "lesson-course-connecting-e4-dco-4",
    courseId: "course-connecting-e4-dco",
    title: "Economy 4.0 ↔ DCO Link Check",
    type: "quiz",
    orderIndex: 4,
    estimatedDurationMinutes: 10,
    content: "A short quiz and scenarios to test how well you can connect Economy 4.0 shifts to DCO implications.",
  },
  {
    id: "lesson-course-culture-innovation-e4-1",
    courseId: "course-culture-innovation-e4",
    title: "Why Innovation Cultures Fail",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 12,
    content: "Unpacks common myths and pitfalls that undermine innovation cultures.",
  },
  {
    id: "lesson-course-culture-innovation-e4-2",
    courseId: "course-culture-innovation-e4",
    title: "Conditions for Everyday Experimentation",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 18,
    content: "Describes the conditions teams need to experiment safely and frequently.",
  },
  {
    id: "lesson-course-culture-innovation-e4-3",
    courseId: "course-culture-innovation-e4",
    title: "Aligning Innovation with Customer and Economic Value",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 18,
    content: "Connects innovation efforts to clear customer outcomes and Economy 4.0 value creation.",
  },
  {
    id: "lesson-course-culture-innovation-e4-4",
    courseId: "course-culture-innovation-e4",
    title: "Designing Simple Innovation Practices",
    type: "outro",
    orderIndex: 4,
    estimatedDurationMinutes: 10,
    content: "Helps you choose and design a few simple practices to strengthen innovation culture.",
  },
  {
    id: "lesson-course-dbp-as-dco-backbone-1",
    courseId: "course-dbp-as-dco-backbone",
    title: "Why DCOs Need Digital Business Platforms",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 12,
    content: "Explains why DBPs are the backbone of Digital Cognitive Organizations.",
  },
  {
    id: "lesson-course-dbp-as-dco-backbone-2",
    courseId: "course-dbp-as-dco-backbone",
    title: "Mapping DCO Needs to DBP Towers",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 18,
    content: "Shows how different DBP towers support specific DCO needs and capabilities.",
  },
  {
    id: "lesson-course-dbp-as-dco-backbone-3",
    courseId: "course-dbp-as-dco-backbone",
    title: "Designing a DBP-Enabled DCO Blueprint",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 18,
    content: "Guides you to create a high-level blueprint of your DCO with the DBP as its backbone.",
  },
  {
    id: "lesson-course-dbp-as-dco-backbone-4",
    courseId: "course-dbp-as-dco-backbone",
    title: "Roadmapping DBP Investments for DCO",
    type: "outro",
    orderIndex: 4,
    estimatedDurationMinutes: 10,
    content: "Helps you outline which DBP investments matter most for your DCO journey.",
  },
  {
    id: "lesson-course-designing-plt-e4-1",
    courseId: "course-designing-plt-e4",
    title: "Introducing Perfect Life Transactions (PLTs)",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 12,
    content: "Defines Perfect Life Transactions and explains why they sit at the center of Economy 4.0.",
  },
  {
    id: "lesson-course-designing-plt-e4-2",
    courseId: "course-designing-plt-e4",
    title: "Mapping Critical Transactions in Your Context",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 18,
    content: "Guides you through identifying and mapping the most important life or business transactions in your domain.",
  },
  {
    id: "lesson-course-designing-plt-e4-3",
    courseId: "course-designing-plt-e4",
    title: "Defining “Perfect” and Spotting Gaps",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 18,
    content: "Helps you define what “perfect” means for key transactions and surface gaps between today and that ideal.",
  },
  {
    id: "lesson-course-designing-plt-e4-4",
    courseId: "course-designing-plt-e4",
    title: "Prioritizing and Acting on PLT Opportunities",
    type: "outro",
    orderIndex: 4,
    estimatedDurationMinutes: 10,
    content: "Wraps up with a simple prioritization approach and next steps for improving your highest-value PLTs.",
  },
  {
    id: "lesson-course-designing-plt-org-1",
    courseId: "course-designing-plt-org",
    title: "PLTs Inside the Organization",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 12,
    content: "Recaps PLTs and explains how they show up inside internal and external organizational journeys.",
  },
  {
    id: "lesson-course-designing-plt-org-2",
    courseId: "course-designing-plt-org",
    title: "Mapping High-Value Organizational Transactions",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 18,
    content: "Guides you to map internal and external transactions that matter most for value and risk.",
  },
  {
    id: "lesson-course-designing-plt-org-3",
    courseId: "course-designing-plt-org",
    title: "Assessing and Redesigning PLTs",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 18,
    content: "Walks through assessing current PLTs and designing improved versions.",
  },
  {
    id: "lesson-course-designing-plt-org-4",
    courseId: "course-designing-plt-org",
    title: "Building a PLT Improvement Backlog",
    type: "outro",
    orderIndex: 4,
    estimatedDurationMinutes: 10,
    content: "Helps you turn PLT insights into a prioritized backlog of improvements.",
  },
  {
    id: "lesson-course-leading-workforce-4-0-1",
    courseId: "course-leading-workforce-4-0",
    title: "What Is Workforce 4.0?",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 10,
    content: "Defines Workforce 4.0 and highlights how work, roles, and skills are changing.",
  },
  {
    id: "lesson-course-leading-workforce-4-0-2",
    courseId: "course-leading-workforce-4-0",
    title: "Shifting Roles and Skills in Workforce 4.0",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 15,
    content: "Explores how roles evolve when humans collaborate with intelligent systems and automation.",
  },
  {
    id: "lesson-course-leading-workforce-4-0-3",
    courseId: "course-leading-workforce-4-0",
    title: "Identifying Capability Gaps",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 15,
    content: "Helps you map current capabilities, surface gaps, and think through reskilling and upskilling needs.",
  },
  {
    id: "lesson-course-leading-workforce-4-0-4",
    courseId: "course-leading-workforce-4-0",
    title: "Workforce 4.0 in Your Organization",
    type: "quiz",
    orderIndex: 4,
    estimatedDurationMinutes: 10,
    content: "Uses scenarios and reflection questions to assess how well you can apply Workforce 4.0 ideas locally.",
  },
  {
    id: "lesson-course-measuring-success-e4-1",
    courseId: "course-measuring-success-e4",
    title: "Why Traditional Metrics Fall Short",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 10,
    content: "Explains why traditional metrics often fail in digital, platform-driven contexts.",
  },
  {
    id: "lesson-course-measuring-success-e4-2",
    courseId: "course-measuring-success-e4",
    title: "From Vanity Metrics to Value Metrics",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 15,
    content: "Shows how to distinguish vanity metrics from metrics linked to real value.",
  },
  {
    id: "lesson-course-measuring-success-e4-3",
    courseId: "course-measuring-success-e4",
    title: "Designing a Simple Measurement Stack",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 15,
    content: "Guides you through designing a minimal set of leading and lagging indicators for digital initiatives.",
  },
  {
    id: "lesson-course-measuring-success-e4-4",
    courseId: "course-measuring-success-e4",
    title: "Metrics in Practice",
    type: "quiz",
    orderIndex: 4,
    estimatedDurationMinutes: 10,
    content: "Uses examples to test whether you can identify good and bad metrics in real scenarios.",
  },
  {
    id: "lesson-course-monetizing-data-1",
    courseId: "course-monetizing-data",
    title: "Data as an Asset, Not Exhaust",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 15,
    content: "Reframes data from a by-product of operations to a strategic asset.",
  },
  {
    id: "lesson-course-monetizing-data-2",
    courseId: "course-monetizing-data",
    title: "Data Value Patterns",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 20,
    content: "Introduces key data value patterns such as",
  },
  {
    id: "lesson-course-strategic-ai-advantage-1",
    courseId: "course-strategic-ai-advantage",
    title: "AI as a Strategic Capability",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 15,
    content: "Frames AI as a core strategic capability rather than a set of isolated projects.",
  },
  {
    id: "lesson-course-strategic-ai-advantage-2",
    courseId: "course-strategic-ai-advantage",
    title: "Aligning AI Initiatives with Strategy",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 20,
    content: "Shows how to align AI initiatives to clear strategic objectives and value drivers.",
  },
  {
    id: "lesson-course-strategic-ai-advantage-3",
    courseId: "course-strategic-ai-advantage",
    title: "Building an AI Portfolio",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 20,
    content: "Guides you to group AI initiatives into a simple portfolio with clear priorities and risks.",
  },
  {
    id: "lesson-course-strategic-ai-advantage-4",
    courseId: "course-strategic-ai-advantage",
    title: "Measuring Strategic Impact of AI",
    type: "outro",
    orderIndex: 4,
    estimatedDurationMinutes: 10,
    content: "Helps you define outcome-based metrics to monitor the impact of your AI portfolio.",
  },
  {
    id: "lesson-course-trust-security-e4-1",
    courseId: "course-trust-security-e4",
    title: "Trust in a Hyper-Connected Economy",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 15,
    content: "Introduces digital trust and why it is fragile in a highly connected, data-rich environment.",
  },
  {
    id: "lesson-course-trust-security-e4-2",
    courseId: "course-trust-security-e4",
    title: "Security, Privacy and Resilience Basics",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 20,
    content: "Covers key concepts in security, privacy, and resilience relevant to Economy 4.0 organizations.",
  },
  {
    id: "lesson-course-trust-security-e4-3",
    courseId: "course-trust-security-e4",
    title: "Balancing Protection and Innovation",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 20,
    content: "Explores how to protect assets while still enabling experimentation and innovation.",
  },
  {
    id: "lesson-course-trust-security-e4-4",
    courseId: "course-trust-security-e4",
    title: "Trust and Security Scenario Lab",
    type: "quiz",
    orderIndex: 4,
    estimatedDurationMinutes: 10,
    content: "Uses short scenarios to test how you would balance risk, trust, and innovation in practice.",
  },
  {
    id: "lesson-course-understanding-economy-4-0-1",
    courseId: "course-understanding-economy-4-0",
    title: "Setting the Stage for Economy 4.0",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 10,
    content: "Introduces the shift from earlier industrial eras to Economy 4.0 and why this new context matters.",
  },
  {
    id: "lesson-course-understanding-economy-4-0-2",
    courseId: "course-understanding-economy-4-0",
    title: "From Industry 1.0 to 4.0",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 15,
    content: "Walks through the evolution from Industry 1.0 to 4.0, highlighting key milestones and shifts.",
  },
  {
    id: "lesson-course-understanding-economy-4-0-3",
    courseId: "course-understanding-economy-4-0",
    title: "Core Drivers of Economy 4.0",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 15,
    content: "Explores the main drivers of Economy 4.0, including data, platforms, AI, and ecosystems.",
  },
  {
    id: "lesson-course-understanding-economy-4-0-4",
    courseId: "course-understanding-economy-4-0",
    title: "Check Your Understanding of Economy 4.0",
    type: "quiz",
    orderIndex: 4,
    estimatedDurationMinutes: 10,
    content: "A short knowledge check using scenarios and questions to reinforce key Economy 4.0 concepts.",
  },
  {
    id: "lesson-course-using-ai-for-advantage-e4-1",
    courseId: "course-using-ai-for-advantage-e4",
    title: "Moving Beyond AI Hype",
    type: "intro",
    orderIndex: 1,
    estimatedDurationMinutes: 15,
    content: "Frames AI as a strategic capability and cleans up common misconceptions and hype.",
  },
  {
    id: "lesson-course-using-ai-for-advantage-e4-2",
    courseId: "course-using-ai-for-advantage-e4",
    title: "Identifying High-Value AI Use Cases",
    type: "standard",
    orderIndex: 2,
    estimatedDurationMinutes: 20,
    content: "Teaches a simple pattern for spotting and qualifying high-value AI use cases in your context.",
  },
  {
    id: "lesson-course-using-ai-for-advantage-e4-3",
    courseId: "course-using-ai-for-advantage-e4",
    title: "From Automation to Augmentation",
    type: "standard",
    orderIndex: 3,
    estimatedDurationMinutes: 20,
    content: "Compares automation and augmentation and explores where each makes the most strategic sense.",
  },
  {
    id: "lesson-course-using-ai-for-advantage-e4-4",
    courseId: "course-using-ai-for-advantage-e4",
    title: "Linking AI to Business Outcomes",
    type: "outro",
    orderIndex: 4,
    estimatedDurationMinutes: 10,
    content: "Guides you to write a simple outcomes-first statement for each AI initiative.",
  },
];
